server:
  port: 8080

spring:
  application:
    name: sales-management-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://100.78.133.11:1776/sales_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
