server:
  port: 8080

spring:
  application:
    name: sales-management-backend
  datasource:
    url: jdbc:h2:mem:salesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
