CREATE TABLE IF NOT EXISTS online_orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  store_id BIGINT NOT NULL,
  channel_id BIGINT NOT NULL,
  external_order_id VARCHAR(100) NOT NULL,
  status VARCHAR(30) NOT NULL,
  external_order_number VARCHAR(100),
  buyer_name VARCHAR(200),
  buyer_phone VARCHAR(30),
  shipping_address VARCHAR(255),
  subtotal DECIMAL(15,2) NOT NULL,
  discount_amount DECIMAL(15,2) NOT NULL,
  shipping_fee DECIMAL(15,2) NOT NULL,
  total_amount DECIMAL(15,2) NOT NULL,
  items_json JSON,
  raw_payload JSON,
  synced_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_online_orders_store_channel_ext (store_id, channel_id, external_order_id),
  INDEX idx_online_orders_store_created (store_id, created_at),
  INDEX idx_online_orders_store_status (store_id, status),
  INDEX idx_online_orders_store_channel (store_id, channel_id)
);

